export default {
  RU: {
    LOADING: "загрузка..",
    SEARCHING: "поиск..",
    VIDEO_ERROR: "Ошибка при загрузке видео",
    VIDEO_RELOAD: "Обновить",
    NOT_IN_PLACE: "Возможно, Вы не находитесь в зоне выставки",
    NOTIFICATION_VIDEO_MIMPI: "Доступно управление инсталляцией",
    HIDE: "скрыть",
    OPEN: "открыть",
    CONFIRM_CLEAR_ATTACHMENT: "Удалить?",
    FEEDBACK_FILL_NAME: "Укажите ваше имя",
    FEEDBACK_TITLE: 'Отзыв',
    FEEDBACK_SHARE: 'Поделиться',
    YOUR_NAME: 'Ваше имя',
    YOUR_OPINION: 'Ваше мнение',
    VIDEO: 'видео',
    PHOTO: 'фото',
    FROM_ALBUM: 'из альбома',
  },
  EN: {
    LOADING: "loading..",
    SEARCHING: "searching..",
    VIDEO_ERROR: "Loading video error",
    VIDEO_RELOAD: "Retry",
    NOT_IN_PLACE: "Maybe You're not in the Mars exhibition",
    NOTIFICATION_VIDEO_MIMPI: "Its available to control exposition",
    HIDE: "hide",
    OPEN: "open",
    CONFIRM_CLEAR_ATTACHMENT: "Remove?",
    FEEDBACK_FILL_NAME: "Fill your name, please",
    FEEDBACK_TITLE: 'Feedback',
    FEEDBACK_SHARE: 'Share via',
    YOUR_NAME: 'Your name',
    YOUR_OPINION: 'Your opinion',
    VIDEO: 'video',
    PHOTO: 'photo',
    FROM_ALBUM: 'from album',
  }
}